[workspace]
authors = ["Era Dorta <e.dorta@tudelft.nl>", "Shaad Alaka <s.alaka@tudelft.nl>"]
channels = ["pytorch3d", "pytorch", "nvidia", "conda-forge"]
name = "mvdust3r"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.1.1,<26"
python = "3.11.*"
pytorch = ">=2.4.1,<3" # Original was ==2.5.1 but pytorch3d only supports up to 2.4.1
torchvision = ">=0.19.1,<0.21"
pytorch-cuda = "11.8.*"
pytorch3d = { version = "*", channel = "pytorch3d" }

[pypi-dependencies]
imageio = {extras = ["ffmpeg"] }
numpy = ">=1.26.4" # Original was ==1.26.4 but we had to allow upgrades
pyglet = "<2"
huggingface-hub = {extras = ["torch"], version = ">=0.22"}
gsplat = "==1.4.0"
torchmetrics = {extras = ["image"], version = "==1.6.0"}
pillow = ">=9.4.0" # "Original was >=11.0.0 but we had to downgrade"

# Other deps that had no version specifiers in the requirements.txt file
roma = ">=1.5.4, <2"
gradio = ">=5.43.1, <6"
matplotlib = ">=3.10.5, <4"
tqdm = ">=4.67.1, <5"
opencv-python = ">=4.11.0.86, <5"
scipy = ">=1.16.1, <2"
einops = ">=0.8.1, <0.9"
trimesh = ">=4.7.4, <5"
tensorboard = ">=2.20.0, <3"
h5py = ">=3.14.0, <4"
scikit-learn = ">=1.7.1, <2"
tensorflow = ">=2.20.0, <3"

# # Installing pytorch3d as a wheel instead of as a conda package. 
# # This fails with ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' because we have a too old version
# # in the Robot-PC
# pytorch3d = "==0.7.8+5043d15pt2.5.1cu118" # Last commit, pytorch 2.5.1 and cuda 11.8

# [pypi-options]
# # This is the index for the pytorch3d wheel
# extra-index-urls = ["https://miropsota.github.io/torch_packages_builder"]
